version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb-container
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: TP
    ports:
      - "3307:3306"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-container
    ports:
      - "3000:3000"
    depends_on:
      - mariadb


volumes:
  db_data: # Volume pour stocker les données MariaDB
