version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb-container
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: TP
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql  # Monte le volume global db_data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-container
    ports:
      - "3001:3000"
    depends_on:
      - mariadb

volumes:
  db_data:  # Déclaration globale du volume
